HW-7 solution
mate-academy/layout_snake pull request #101
Opened 2019-07-26 11:15 UTC by KosBelozyorov

[DEMO LINK](https://KosBelozyorov.github.io/layout_snake/)
[UPDATE TEST REPORT LINK](https://KosBelozyorov.github.io/layout_snake/report/html_report/)

2019-07-26 13:01 UTC, irenhh requested changes

2019-07-26 13:01 UTC, irenhh commented on src/style.css
> +* {
do not overuse `*`-selector, style the elements you need,
use margin: 0 for body tag

2019-07-26 13:04 UTC, KosBelozyorov commented
fixed style.css

2019-07-26 13:22 UTC, irenhh approved these changes

2019-07-26 13:22 UTC, irenhh commented on src/style.css
> +  padding: 0;
body doesn't have default paddings

2019-07-28 10:54 UTC, KosBelozyorov commented
fix style.css

2025-09-21 21:09 UTC, closed without merging