Solution was added
mate-academy/layout_snake pull request #1056
Opened 2021-12-08 12:00 UTC by Mazyt81

2021-12-08 16:38 UTC, vkryvytskyy requested changes, later dismissed

2021-12-08 16:38 UTC, vkryvytskyy commented on src/index.html
> +      <div class="block block1">1</div>
```suggestion
      <div class="block">1</div>
```
Используй nth-child

2021-12-08 16:38 UTC, vkryvytskyy commented on src/index.html
> +      <div class="break"></div>
Тебе не надо добавлять в верстку новые блоки

2021-12-08 16:38 UTC, vkryvytskyy commented on src/style.css
> +  display: block;
Задай это свойство всем `.block`, а не каждому отдельно

2021-12-08 16:38 UTC, vkryvytskyy commented on readme.md
> +- [DEMO LINK](https://Mazyt81.github.io/layout_snake/)
https://user-images.githubusercontent.com/38065883/145247093-7e3e29cd-7d53-46e8-9d8d-66d5e1ba8948.mov

2022-01-31 14:52 UTC, varseniuk approved these changes

2024-06-11 15:38 UTC, closed without merging