Create blocks with a media query
mate-academy/layout_snake pull request #1189
Opened 2022-02-16 15:36 UTC by ivan-kadykalo

- [DEMO LINK](https://ivan-kadykalo.github.io/layout_snake/)
- [TEST REPORT LINK](https://ivan-kadykalo.github.io/layout_snake/report/html_report/)

2022-02-17 14:48 UTC, illiarerun requested changes
Good job 🔥  few little fixes left:

2022-02-17 14:48 UTC, illiarerun commented on src/style.css
> +  padding: 0;
body doesn't have default paddings
```suggestion
```

2022-02-17 14:48 UTC, illiarerun commented on src/style.css
> +    min-width: calc(100% / 3);
here too

2022-02-17 14:48 UTC, illiarerun commented on src/style.css
> +  justify-content: center;
do you really need it?
```suggestion
```

2022-02-22 06:04 UTC, MaksimusCRS requested changes

2022-02-22 06:04 UTC, MaksimusCRS commented on src/style.css
> +@media (min-width: 600px) and (max-width: 899px) {
Что-то тут не так... 
Ты должен задавать только 1 ограничение

2022-02-22 06:56 UTC, ivan-kadykalo commented on src/style.css
> +@media (min-width: 600px) and (max-width: 899px) {
Твоя правда. Видалив верхню max-width та змінив місцями з попереднім media.

2022-02-23 05:42 UTC, MaksimusCRS approved these changes
GJ!

2023-08-08 17:41 UTC, closed without merging