snake
mate-academy/layout_snake pull request #1199
Opened 2022-02-17 12:18 UTC by kkiirill

[DEMO LINK](https://kkiirill.github.io/layout_snake/)

2022-02-18 11:21 UTC, ArtemTopolskyi requested changes

2022-02-18 11:21 UTC, ArtemTopolskyi commented on src/style.css
> +}
совершенно одинаковые правила

2022-02-21 09:34 UTC, danylo-onishchuk requested changes

2022-02-21 09:34 UTC, danylo-onishchuk commented on src/style.css
> +
пустая строка?

2022-02-21 09:34 UTC, danylo-onishchuk commented on src/style.css
> +
?

2022-02-21 09:34 UTC, danylo-onishchuk commented on src/style.css
> +  flex: 1 1 33%;
use flex basis

2022-02-21 09:34 UTC, danylo-onishchuk commented on src/style.css
> +  background: red;
use colors or rgb

2022-02-21 11:24 UTC, danylo-onishchuk approved these changes

2023-01-03 18:38 UTC, closed without merging