Add layout_snake
mate-academy/layout_snake pull request #1206
Opened 2022-02-17 17:10 UTC by YegorKochetkov

https://YegorKochetkov.github.io/layout_snake/
https://YegorKochetkov.github.io/layout_snake/report/html_report/

2022-02-21 18:20 UTC, ivan-kadykalo requested changes
Nice code))
Only couple things left

2022-02-21 18:20 UTC, ivan-kadykalo commented on src/style.css
> +  min-width: 300px;
Use `flex-basis` instead of `min-width`

2022-02-21 18:20 UTC, ivan-kadykalo commented on src/style.css
> +    width: 33.33%;
will be better to use `calc(100% / 3)` and `flex-basis`

2022-02-21 18:20 UTC, ivan-kadykalo commented on src/style.css
> +    width: 50%;
here also

2022-02-21 18:29 UTC, ivan-kadykalo commented
For some reasons your links doesn't work. 
![image](https://user-images.githubusercontent.com/57747481/155009827-f37d930b-c89a-4bcb-b4a2-e33227c3b5ae.png)

2022-02-22 06:06 UTC, MaksimusCRS approved these changes
GJ!

2022-11-01 22:09 UTC, closed without merging