snake
mate-academy/layout_snake pull request #1248
Opened 2022-02-21 12:15 UTC by DikanevYura

2022-02-21 15:14 UTC, ArtemTopolskyi requested changes

2022-02-21 15:14 UTC, ArtemTopolskyi commented on src/index.html
> +      </div>
```suggestion
      <div class="block block--1">1</div>
```
контента не так много, думаю нет необходимости выносить на новую строку

2022-02-21 15:14 UTC, ArtemTopolskyi commented on src/style.css
> +  .container:before {
здесь точно необходим before элемент?

2022-02-21 15:14 UTC, ArtemTopolskyi commented on src/style.css
> +  }
у разных flex child'ов не должен быть один и тот же order

2022-02-21 15:14 UTC, ArtemTopolskyi commented on src/style.css
> +    order: -1;
не уверен, что тебе необходимы отрицательные ордеры, перепиши с позитивными

2022-02-22 14:15 UTC, DikanevYura commented on src/style.css
> +  .container:before {
да он нужен, если его не будет, не проходит тест, и блоки тогда совсем по другому себе ведут

2022-02-22 14:20 UTC, DikanevYura commented on src/index.html
> +      </div>
сдесь согласен, исправил

2022-02-22 14:20 UTC, DikanevYura commented on src/style.css
> +  }
а как мне сделать тогда?

2022-03-24 11:11 UTC, varseniuk requested changes
Не використовуй від'ємний order для цього завдання

2022-03-24 11:11 UTC, varseniuk commented on src/style.css
> +@media (min-width: 600px) and (max-width: 899px) {
не використовуй від'ємний order. Для цього медіа-запиту, наприклад, потрібно просто вказати flex-basis: 50% для block, і поміняти order для третього і четвертого блоків (поставити його на 4 і 3, відповідно)

2022-03-24 11:11 UTC, varseniuk commented on src/style.css
> +  .container:before {
Не зрозуміло, для чого потрібен цей псевдоелемент. Все, що потрібно для цього завдання - це міняти flex-basis та order для блоків при певних медіа-запитах

2022-03-24 11:11 UTC, varseniuk commented on src/style.css
> +@media (min-width: 900px) {
тут потрібно вказати flex-basis: 33% та поміняти order для 4 і 6 блоків

2022-09-24 13:10 UTC, closed without merging