snake layout done
mate-academy/layout_snake pull request #1283
Opened 2022-03-29 13:03 UTC by ZUBOV-ILLIA

- [DEMO LINK](https://ZUBOV-ILLIA.github.io/layout_snake/)
- [TEST REPORT LINK](https://ZUBOV-ILLIA.github.io/layout_snake/report/html_report/)

2022-03-31 16:29 UTC, Denchepornyuk requested changes
<img width="1440" alt="Screenshot 2022-03-31 at 19 28 25" src="https://user-images.githubusercontent.com/37452763/161104617-bcc79068-14d0-4f5c-8f3d-a9f9cfe38614.png">

blocks should occupy the entire width 100%

2022-04-01 08:42 UTC, Denchepornyuk requested changes

2022-04-01 08:42 UTC, Denchepornyuk commented on src/index.html
> +      <div class="block">1</div>
add class `block--1, block--2, ...` for each block and remove `:nth-child` from css

2022-04-01 13:43 UTC, denys-cheporniuk approved these changes

2025-03-11 09:16 UTC, closed without merging