Snake DONE
mate-academy/layout_snake pull request #1304
Opened 2022-04-01 19:09 UTC by JeniaGaidukov

- [DEMO LINK](https://JeniaGaidukov.github.io/layout_snake/)
- [TEST REPORT LINK](https://JeniaGaidukov.github.io/layout_snake/report/html_report/)

2022-04-04 08:51 UTC, Bohdan-Maksymiuk requested changes
<img width="1440" alt="Screenshot 2022-04-04 at 11 47 36" src="https://user-images.githubusercontent.com/94289038/161508385-befdc99f-0e16-4abc-b8d2-3a35b902222c.png">
Good job, but is it the correct order? Fix media queries
And you can use just two media there: before 600px and before 900px. Try to rewrite

2022-04-04 08:51 UTC, Bohdan-Maksymiuk commented on src/index.html
> +      <div class="box box_1">1</div>
```suggestion
      <div class="box box--1">1</div>
```

2022-04-04 16:24 UTC, JeniaGaidukov commented on src/index.html
> +      <div class="box box_1">1</div>
Перевірте будь-ласка, виправив, дякую!

2022-04-13 07:41 UTC, marina-tilniak requested changes

2022-04-13 07:41 UTC, marina-tilniak commented on src/index.html
>  </html>
```suggestion
  </body>
</html>
```

2022-04-13 07:41 UTC, marina-tilniak commented on src/index.html
> +  <head>
same here

2022-04-22 06:55 UTC, Bohdan-Maksymiuk approved these changes

2022-04-23 09:40 UTC, closed without merging