Created snake task
mate-academy/layout_snake pull request #1382
Opened 2022-05-08 08:40 UTC by olya-yevsieienko

- [DEMO LINK](https://olya-yevsieienko.github.io/layout_snake/)
- [TEST REPORT LINK](https://olya-yevsieienko.github.io/layout_snake/report/html_report/)

2022-05-11 16:56 UTC, jstmpelowycz requested changes
A few things left to fix, and you're done

2022-05-11 16:56 UTC, jstmpelowycz commented on src/style.css
> +@media (max-width: 599px) {
That is more obvious to create a media query this way
```suggestion
@media (min-width: 600px) {
```

2022-05-11 16:56 UTC, jstmpelowycz commented on src/style.css
> +@media (max-width: 899px) {
That is more obvious to create a media query this way
```suggestion
@media (min-width: 900px) {
```

2022-05-11 16:56 UTC, jstmpelowycz commented on src/style.css
> +  flex-basis: 33.3%;
```suggestion
  flex-basis: calc(100% / 3);
```

2022-05-11 17:13 UTC, jstmpelowycz commented on src/style.css
> +.block {
The width of each block should be not less than its height (300px)

2022-05-11 17:14 UTC, jstmpelowycz requested changes

2022-05-11 17:14 UTC, jstmpelowycz commented on src/style.css
> +.block {
The width of each block should be not less than its height (300px)

2022-05-13 07:31 UTC, jstmpelowycz requested changes
Small hints left

2022-05-13 07:31 UTC, jstmpelowycz commented on src/style.css
> +.block {
Add `min-width`

2022-05-13 07:31 UTC, jstmpelowycz commented on src/style.css
> +@media (min-width: 600px) and (max-width: 899px) {
Do you need `max-width`?

2022-05-13 07:38 UTC, olya-yevsieienko commented
I have a question, if I set flex-basic for each block, do I still need to
write min-width?

пт, 13 мая 2022 г. в 10:31, Dmytro Pelovych ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Small hints left
> ------------------------------
>
> In src/style.css
> <https://github.com/mate-academy/layout_snake/pull/1382#discussion_r872083020>
> :
>
> > +
> ***@***.*** (min-width: 900px) {
> +  .block {
> +    flex-basis: calc(100% / 3);
> +  }
> +
> +  .block--4 {
> +    order: 2;
> +  }
> +
> +  .block--5 {
> +    order: 1;
> +  }
> +}
> +
> ***@***.*** (min-width: 600px) and (max-width: 899px) {
>
> Do you need max-width?
> ------------------------------
>
> In src/style.css
> <https://github.com/mate-academy/layout_snake/pull/1382#discussion_r872081680>
> :
>
> > +html {
> +  font-family: Arial, Helvetica, sans-serif;
> +  font-size: 100px;
> +
> +}
> +
> +body {
> +  margin: 0;
> +}
> +
> +.container {
> +  display: flex;
> +  flex-wrap: wrap;
> +}
> +
> +.block {
>
> Add min-width
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/layout_snake/pull/1382#pullrequestreview-971812716>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO2L24I7EKYGIXNIGHCLMTTVJYAOZANCNFSM5VLTQXOA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-11 08:31 UTC, olya-yevsieienko commented
Okay, thanks! I fixed it.

ср, 11 мая 2022 г. в 20:14, Dmytro Pelovych ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/style.css
> <https://github.com/mate-academy/layout_snake/pull/1382#discussion_r870562374>
> :
>
> > +html {
> +  font-family: Arial, Helvetica, sans-serif;
> +  font-size: 100px;
> +
> +}
> +
> +body {
> +  margin: 0;
> +}
> +
> +.container {
> +  display: flex;
> +  flex-wrap: wrap;
> +}
> +
> +.block {
>
> The width of each block should be not less than its height (300px)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/layout_snake/pull/1382#pullrequestreview-969730035>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO2L24IK2LSYKW4T3AQ77B3VJPTHPANCNFSM5VLTQXOA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-07 10:57 UTC, closed without merging