Develop
mate-academy/layout_snake pull request #1440
Opened 2022-05-22 12:16 UTC by constantweb

[DEMO LINK](https://constantweb.github.io/layout_snake/)
[TEST REPORT LINK](https://constantweb.github.io/layout_snake/report/html_report/)

2022-05-23 13:04 UTC, vkryvytskyy requested changes

2022-05-23 13:04 UTC, vkryvytskyy commented on src/index.html
> +      ">1</div>
```suggestion
      <div class="box__block">1</div>
```
Не надо отдельные классы для цвета и порядка, используй `:nth-child` селектор, и в нем прописывай оба правила

2022-05-24 09:56 UTC, constantweb commented
Внес изменения
[DEMO LINK](https://constantweb.github.io/layout_snake/)
[TEST REPORT LINK](https://constantweb.github.io/layout_snake/report/html_report/)

2022-07-12 08:36 UTC, alexandra-protyanova requested changes

2022-07-12 08:36 UTC, alexandra-protyanova commented on src/index.html
> +      ">1</div>
Agree, Fix this comment

2022-07-13 06:26 UTC, constantweb commented
Внес изменения
[DEMO LINK](https://constantweb.github.io/layout_snake/)
[TEST REPORT LINK](https://constantweb.github.io/layout_snake/report/html_report/)

2022-07-14 09:52 UTC, alexandra-protyanova commented
Ты можешь не дублировать ссылки, после деплоя они они обновляются

2022-07-14 09:54 UTC, alexandra-protyanova requested changes

2022-07-14 09:54 UTC, alexandra-protyanova commented on src/index.html
> +        box__block--color_6
delete classes for color, they are not changing

2022-07-14 09:54 UTC, alexandra-protyanova commented on src/index.html
> +        box__block--color_6
Почему-то нет изменений в файлах, попробуй что-то изменить и снова запушить

2022-08-16 06:33 UTC, constantweb commented on src/index.html
> +        box__block--color_6
![Screenshot_2](https://user-images.githubusercontent.com/46863491/184813083-8c58cf13-c840-45e9-bbf3-deee2fa21536.png)

2022-08-16 06:34 UTC, constantweb commented on src/index.html
> +        box__block--color_6
Перейшов за посиланям, таких класів немає. Не розумію чтому так

2022-08-23 12:31 UTC, closed without merging