flex
mate-academy/layout_snake pull request #352
Opened 2020-07-03 15:21 UTC by zarva6596

[DEMO LINK](https://zarva6596.github.io/layout_snake/)
[TEST REPORT LINK](https://zarva6596.github.io/layout_snake/report/html_report/)

2020-07-03 15:49 UTC, irenhh requested changes
check the page for big screens, you have white spaces on edges

no need to repeat orders if they don't change

2020-07-03 15:49 UTC, irenhh commented on src/index.html
> +          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
```suggestion
    <meta 
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    >
```
formatting

2020-07-03 15:49 UTC, irenhh commented on src/style.css
> +  font-size: 100px;
use this value for those elements you need

2020-07-06 12:11 UTC, mykola-yarchuk requested changes

2020-07-06 12:11 UTC, vsm2k17 commented on src/style.css
> +@media screen and (min-width: 600px) and (max-width: 900px) {
no need to set min and max, one thing is enough, (min-width in your case)

2020-07-06 12:11 UTC, vsm2k17 commented on src/style.css
> +}
no need to repeat orders if they don't change, 
in this case, they already in right order.

2020-07-06 16:13 UTC, danheim approved these changes

2024-07-03 16:33 UTC, closed without merging