Develop
mate-academy/layout_snake pull request #684
Opened 2021-05-27 16:32 UTC by Vivdyuk

- [DEMO LINK](https://vivdyuk.github.io/layout_snake/)
- [TEST REPORT LINK](https://vivdyuk.github.io/layout_snake/report/html_report/)

2021-05-29 07:38 UTC, ArtemTopolskyi requested changes
На широких экранах не соответствует условию:
![image](https://user-images.githubusercontent.com/57574816/120062277-fdf93980-c069-11eb-83e8-e533cd0f5954.png)

![image](https://user-images.githubusercontent.com/57574816/120062279-018cc080-c06a-11eb-97ce-acd8631f6fc6.png)

2021-05-29 07:39 UTC, ArtemTopolskyi requested changes

2021-05-29 07:39 UTC, ArtemTopolskyi commented on src/style.css
> +[class*="block"] {
Просто задай class="block"

2021-05-31 12:10 UTC, aionova requested changes
On wide screens there still need to be not more than 3 blocks in a row. 
<img width="1440" alt="Screenshot 2021-05-31 at 15 09 59" src="https://user-images.githubusercontent.com/68023426/120191175-465b5780-c222-11eb-8be7-113a25bbf642.png">

2021-05-31 14:20 UTC, Vivdyuk commented
> On wide screens there still need to be not more than 3 blocks in a row.
> <img alt="Screenshot 2021-05-31 at 15 09 59" width="1440" src="https://user-images.githubusercontent.com/68023426/120191175-465b5780-c222-11eb-8be7-113a25bbf642.png">

2021-05-31 14:34 UTC, aionova approved these changes
Good job!

2021-05-31 14:35 UTC, Vivdyuk commented
> Good job!

Thanks!

2021-11-09 11:49 UTC, closed without merging