snake
mate-academy/layout_snake pull request #729
Opened 2021-07-01 08:37 UTC by anton-forzun

2021-07-01 14:24 UTC, vkryvytskyy requested changes

2021-07-01 14:24 UTC, vkryvytskyy commented on readme.md
> +- [DEMO LINK](https://anton-forzun.github.io/layout_snake/)
![image](https://user-images.githubusercontent.com/38065883/124140340-10172f00-da91-11eb-82bf-e0fd17aebf12.png)

https://user-images.githubusercontent.com/38065883/124140367-14dbe300-da91-11eb-8d08-1a1b783b4a0a.mov

gh-pages не работают, сделай так же как на видео

2021-07-01 17:06 UTC, anton-forzun commented on readme.md
> +- [DEMO LINK](https://anton-forzun.github.io/layout_snake/)
![image](https://user-images.githubusercontent.com/85868104/124163008-cf76e000-daa7-11eb-87d9-de8046ed45ee.png)

2021-07-01 17:07 UTC, anton-forzun commented on readme.md
> +- [DEMO LINK](https://anton-forzun.github.io/layout_snake/)
В мене нема там gh-pages.що це може бути?

2021-07-02 10:18 UTC, vkryvytskyy commented on readme.md
> +- [DEMO LINK](https://anton-forzun.github.io/layout_snake/)
А ты делал `npm run deploy`?
Если нет - сделай
Если делал - запусти в терминале `git --version`
Если там 2.32 - надо откатиться до 2.31, вот ссылка 
https://stackoverflow.com/questions/67990094/the-library-is-not-added-to-the-git-via-the-git-subtree

2021-07-02 10:19 UTC, vkryvytskyy requested changes
Скинул ссылку как пофиксить gh-pages

2021-07-02 15:00 UTC, anton-forzun commented on readme.md
> +- [DEMO LINK](https://anton-forzun.github.io/layout_snake/)
![image](https://user-images.githubusercontent.com/85868104/124293429-533fd380-db5f-11eb-9626-8ee984002e66.png)
зробив встановив версію 2.31 і gh-pages зявилось

2021-07-05 13:06 UTC, mykola-yarchuk requested changes
![image](https://user-images.githubusercontent.com/35385361/124475891-eb7dc880-ddaa-11eb-82a1-b4cdf05f57e2.png)
потрібно зробити так щоб не було білого зовсім, блоки з цифрами повинні зайвжди займати 100% ширини екрану

2021-07-06 11:39 UTC, mykola-yarchuk requested changes

2021-07-06 11:39 UTC, mykola-yarchuk commented on src/style.css
> +  max-width: 1200px;
це зайве на великих екранах хай розтягується на всю ширину

2021-07-06 11:39 UTC, mykola-yarchuk commented on src/style.css
> +  width: 300px;
зайве

2021-07-06 11:39 UTC, mykola-yarchuk commented on src/style.css
> +    max-width: 1050px;
зайве

2021-07-06 11:39 UTC, mykola-yarchuk commented on src/style.css
> +    max-width: 1199px;
зайве, не обмежуй контейнер

2021-07-06 11:39 UTC, mykola-yarchuk commented on src/style.css
> +@media (min-width: 1050px) {
цей брейкпоінт зайвий хав поводить себе так само як при 900px

2021-07-07 09:18 UTC, vkryvytskyy submitted a review, later dismissed

2021-07-07 09:18 UTC, vkryvytskyy commented on src/style.css
> +}
Вместо этих классов используй nth-child, чтобы задавать стили основываясь на положении элемента в DOM

2021-07-07 09:18 UTC, vkryvytskyy commented on src/style.css
> +}
Этот брейкпоинт надо оставить

2021-07-07 09:18 UTC, vkryvytskyy commented on src/style.css
> +@media (min-width: 1050px) {
А этот закомментированный - удали

2021-07-07 09:20 UTC, vkryvytskyy commented
![image](https://user-images.githubusercontent.com/38065883/124734257-9dd59d00-df1d-11eb-9c6c-6e35b45a15d5.png)
У тебя на gh-pages старая версия, после каждого коммита нужно делать deploy
![image](https://user-images.githubusercontent.com/38065883/124734324-ab8b2280-df1d-11eb-8c2f-4d8a15745487.png)
А у тебя последнее изменение в develop 20 часов назад, а последнее изменение на gh-pages - 5 дней назад

2021-07-08 11:01 UTC, mykola-yarchuk approved these changes

2021-07-08 11:08 UTC, anton-forzun commented on src/style.css
> +
видалив

2021-07-08 11:09 UTC, closed without merging