solution
mate-academy/layout_snake pull request #863
Opened 2021-08-20 13:25 UTC by Tarasulko

- [DEMO LINK](https://tarasulko.github.io/layout_snake/)
- [TEST REPORT LINK](https://tarasulko.github.io/layout_snake/report/html_report/)

2021-08-20 14:36 UTC, herkoss commented
Нужно исправить

<img width="1440" alt="Screenshot 2021-08-20 at 17 35 38" src="https://user-images.githubusercontent.com/61412282/130249761-57d037eb-9b50-4dc9-b019-01602b02380b.png">

2021-08-20 14:38 UTC, herkoss requested changes
Well done!👍
Fix bug with viewport width > 1200px

2021-08-21 10:31 UTC, Tarasulko commented
![image](https://user-images.githubusercontent.com/43114982/130318970-878f713c-16ad-46bc-80ed-4850e9d93a50.png)
Я не можу зрозуміти в чому баг....при 1200 в мене в браузері нормально показує. А при більше 1200 до 1500 (оскільки мінімальна ширина кожного блока повинна бути не менше висоти, тобто 300) показує як на скріні.

2021-08-23 08:26 UTC, OleksiiBlezniuk approved these changes
Good job 👍

2021-08-23 08:26 UTC, OleksiiBlezniuk commented on src/style.css
> +  font-family: Arial, sans-serif;
Шрифты лучше записывать в теге html

2021-08-31 08:20 UTC, OleksiiBlezniuk approved these changes

2024-10-22 13:58 UTC, closed without merging